controller_list:
  - name: fake_arm_1_controller
    type: $(arg fake_execution_type)
    joints:
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
      - arm_joint_4
      - arm_joint_5
  - name: fake_aiming_group_controller
    type: $(arg fake_execution_type)
    joints:
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
      - arm_joint_4
initial:  # Define initial robot poses per group
  - group: arm_1
    pose: start