arm_1:
  # kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  # solve_type: speed
  # kinematics_solver_timeout: 0.2
  # goal_joint_tolerance: 0.02
  # goal_position_tolerance: 0.02
  # goal_orientation_tolerance: 0.02

  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.2
  kinematics_solver_attempts: 3

  # kinematics_solver: bio_ik/BioIKKinematicsPlugin
  # kinematics_solver_search_resolution: 0.01
  # kinematics_solver_timeout: 0.2
  # kinematics_solver_attempts: 1
  

  # kinematics_solver: youbot_arm_kinematics_moveit::KinematicsPlugin
  # kinematics_solver_search_resolution: 0.1
  # kinematics_solver_timeout: 0.1